# Generated by Django 6.0.5 on 2026-06-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
