# Generated by Django 6.0.5 on 2026-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
