# Generated by Django 6.0.6 on 2026-07-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_comment_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
